[package]
name = "quandary"
version = "0.1.0"
authors = ["Matthew Ingwersen <matttpt@gmail.com>"]
edition = "2021"

[profile.release]
codegen-units = 1
lto = true

[dependencies]
arrayvec = "0.7"
log = "0.4"
slab = "0.4"

[dev-dependencies]
lazy_static = "1.4"
