name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --all-features --verbose
    - name: Test
      run: cargo test --all-features --verbose

  code-quality:
    name: Code quality
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    - name: Clippy
      run: cargo clippy --all --all-features -- -D warnings
    - name: rustfmt
      run: cargo fmt --all --check

  docs:
    name: Docs
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - name: Build docs
      env:
        RUSTDOCFLAGS: -D warnings
      run: cargo doc --all-features --no-deps --document-private-items
